import * as yup from "yup";
export const validationSchema = yup.object().shape({
  firstName: yup.string().required(),
  middleName: yup.string(),
  lastName: yup.string().required(),
  email: yup.string().email("Please enter a valid email address").required(),
  mobile: yup.string().matches(/\d{10}/, "Phone number is not valid"),
  address: yup.string(),
  contractType: yup.string().required(),
  startDay: yup.number().min(1).max(31).required(),
  startMonth: yup.number().min(1).max(12).required(),
  startYear: yup.number().min(1900).max(new Date().getFullYear()).required(),
  endDay: yup.number().min(1).max(31).nullable(),
  endMonth: yup.number().min(1).max(12).nullable(),
  endYear: yup.number().min(1900).max(new Date().getFullYear()).nullable(),
  employmentType: yup.string().required(),
  isOngoing: yup.boolean().required(),
  hoursPerWeek: yup.number().min(1).max(168).required(),
});

export const employeeDefaults = {
  firstName: "",
  middleName: "",
  lastName: "",
  email: "",
  mobileNumber: 0o4,
  address: "",
  startDay: 1,
  startMonth: 1,
  startYear: 2023,
  endDay: null,
  endMonth: null,
  endYear: null,
  employmentType: "fullTime",
  isOngoing: true,
  contractType: "permanent",
  hoursPerWeek: 40,
};
